FILE = {'omega': "./parameters/omega.dat",
        'theta0': "./parameters/theta0.dat",
        'theta': "./parameters/theta.dat",
        't': "./parameters/t.dat",
        'R': "./parameters/R.dat",
        'phi': "./parameters/phi.dat",
        'S': "./parameters/S.dat",
        'K': "./parameters/K.dat",
        'eta': "./parameters/eta.dat",
        'alpha': "./parameters/alpha.dat",
        'tau': "./parameters/tau.dat"}
